### ISSUE TITLE
Hi! I have a little problem.

### ISSUE THREAD

**Issue by xhzengAIB** [nigelgrange/WPAttributedMarkup#1]
Hi! @nigelgrange 
Thanks you open source，Gave me great help。

But I'm a little confused is: click event parser together? What is the principle and process?

https://github.com/nigelgrange/WPAttributedMarkup/blob/master/Extras/WPHotspotLabel.m#L42
to：
https://github.com/nigelgrange/WPAttributedMarkup/blob/master/Extras/WPHotspotLabel.m#L50

Jack

**Comment by nigelgrange** [comment]
Hi. Yes, the click parser is part of the 'Extas' package. The principle is that an action block is attached to the attributes of the text and is then located based on the x,y tap position on the text and executed.

The WPAttributedStyleAction class is used to wrap the block and easily add it to the style dictionary.

Please let me know if anything is unclear.

**Comment by xhzengAIB** [comment]
Hi! 
yet！ got it,  Thanks !

**Comment by xhzengAIB** [comment]
Hi! @nigelgrange 
Can you give me skype id? We make friends

Jack
